### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by yesyeahvh123** [dadami-io/lets_scroll#3]
sir how to install, I'm a newbie with no experience ? can you make the button deploy to free platforms like vercel, railway, glitch?

**Comment by ghost** [comment]
1. sorry, but this isn't currently working. even if you install it, it won't work. we'll make it work someday ;)
2. there're no plans to use or support other platforms(only for docker).

this project is just for fun.
I'm not from an English-speaking country, so please understand if my words are awkward.
